#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : perl-Sub-Quote
Version  : 2.006008
Release  : 37
URL      : https://cpan.metacpan.org/authors/id/H/HA/HAARG/Sub-Quote-2.006008.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/H/HA/HAARG/Sub-Quote-2.006008.tar.gz
Summary  : 'Efficient generation of subroutines via string eval'
Group    : Development/Tools
License  : Artistic-1.0-Perl GPL-1.0
Requires: perl-Sub-Quote-license = %{version}-%{release}
Requires: perl-Sub-Quote-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
NAME
Sub::Quote - Efficient generation of subroutines via string eval
SYNOPSIS
package Silly;

%package dev
Summary: dev components for the perl-Sub-Quote package.
Group: Development
Provides: perl-Sub-Quote-devel = %{version}-%{release}
Requires: perl-Sub-Quote = %{version}-%{release}

%description dev
dev components for the perl-Sub-Quote package.


%package license
Summary: license components for the perl-Sub-Quote package.
Group: Default

%description license
license components for the perl-Sub-Quote package.


%package perl
Summary: perl components for the perl-Sub-Quote package.
Group: Default
Requires: perl-Sub-Quote = %{version}-%{release}

%description perl
perl components for the perl-Sub-Quote package.


%prep
%setup -q -n Sub-Quote-2.006008
cd %{_builddir}/Sub-Quote-2.006008

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Sub-Quote
cp %{_builddir}/Sub-Quote-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/perl-Sub-Quote/cf80311fdffd31d348351cedac56a9d497a8c75b || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Sub::Defer.3
/usr/share/man/man3/Sub::Quote.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Sub-Quote/cf80311fdffd31d348351cedac56a9d497a8c75b

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
