#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Sub-Quote
Version  : 2.005001
Release  : 10
URL      : http://search.cpan.org/CPAN/authors/id/H/HA/HAARG/Sub-Quote-2.005001.tar.gz
Source0  : http://search.cpan.org/CPAN/authors/id/H/HA/HAARG/Sub-Quote-2.005001.tar.gz
Summary  : 'Efficient generation of subroutines via string eval'
Group    : Development/Tools
License  : Artistic-1.0-Perl
BuildRequires : buildreq-cpan
BuildRequires : perl(Test::Fatal)
BuildRequires : perl(Try::Tiny)

%description
NAME
Sub::Quote - Efficient generation of subroutines via string eval
SYNOPSIS
package Silly;

%package dev
Summary: dev components for the perl-Sub-Quote package.
Group: Development
Provides: perl-Sub-Quote-devel = %{version}-%{release}

%description dev
dev components for the perl-Sub-Quote package.


%prep
%setup -q -n Sub-Quote-2.005001

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.1Sub/Defer.pm
/usr/lib/perl5/vendor_perl/5.28.1Sub/Quote.pm

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Sub::Defer.3
/usr/share/man/man3/Sub::Quote.3
